### ISSUE TITLE
Documentation does not mention how to set your profile value SS_API_URL

### ISSUE THREAD

**Issue by JaysonBH** [stephendotcarter/gosafely#6]
Documentation does not mention how to set your profile value SS_API_URL='MY_SENDSAFELY_URL'

Where do I get MY_SENDSAFELY_URL ?

Is it needed in order to use the tool or is the key and secret good enough?

**Comment by stephendotcarter** [comment]
Hi Jayson,

I know we already discussed this but for others.
If the file you are trying to download is:
- `https://sendsafely.test.com/receive/?thread=ABCD-EFGH&packageCode=11aa22bb33cc#keyCode=dd44ee55ff66`
Then the `SS_API_URL` would be:
- `https://sendsafely.test.com`

Kind regards,
Stephen
